name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Release target
      run: dotnet build -c Release --no-restore
    - name: Run tests
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Publish
      run: dotnet publish EsoAdv.Cmd/EsoAdv.Cmd.csproj --no-build -c Release--self-contained true 
